#!/bin/bash -x
# Run a command under Valgrind, while following forks and logging to disk.
exec valgrind -v --trace-children=yes \
	--trace-children-skip=/bin/nm,/usr/bin/clang,/bin/rm,/bin/sh,/bin/sed,/bin/ls \
	--track-fds=yes \
	--leak-check=full --show-leak-kinds=all \
	--log-file="var/log-valgrind-%p.txt" \
	$*
